name: CI
on:
  push:
    branches: [master]
  workflow_dispatch:

env:
    emsdk_ver: 3.1.19

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Submodules
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git submodule init
          git submodule update

      - name: Cache emsdk
        id: cache-emsdk
        uses: actions/cache@v3
        with:
          path: emsdk
          key: ${{ runner.os }}-${{ env.emsdk_ver }}

      - name: Install Packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y git

      - if: ${{ steps.cache-emsdk.outputs.cache-hit != 'true' }}
        name: EMSDK
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install ${{ env.emsdk_ver }}
          ./emsdk activate ${{ env.emsdk_ver }}
          mkdir env

      - name: Build
        run: |
          cd emsdk
          export WORKSPACE="${{github.workspace}}/emsdk/env"
          export EMSDK="${{github.workspace}}/emsdk"
          ../build-libs.sh
          cd ..
          ./build.sh

      - name: Create Artifact
        run: |
          mkdir -p artifact/metaparser-js
          cp -r release/* artifact/metaparser-js

      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: metaparser-js
          path: artifact
          retention-days: 1
